### ISSUE TITLE
Can I add the local p2 update site into pom.xml in a Eclipse plug-in project after running `mvn jetty:run`?

### ISSUE THREAD

**Issue by kenshinji** [reficio/p2-maven-plugin#105]
If so, I guess the `<repository>` section is where I should put it in. However I don't know how to fill in `<id>` and `<url>` parts.

**Comment by LorenzoBettini** [comment]
I think for the id you can choose any, for the URL, as said here http://projects.reficio.org/p2-maven-plugin/1.1.0/manual.html, it should be http://localhost:8080/site
