### ISSUE TITLE
Last releases ??!!

### ISSUE THREAD

**Issue by tJeyhun** [reficio/p2-maven-plugin#113]
I can not find last releases in 
repo http://repo.reficio.org/maven/org/reficio/p2-maven-plugin/
where is 1.2.1-SNAPSHOT or 1.2.0 version?

**Comment by cdealti** [comment]
@tJeyhun 1.2.0 is on Maven Central

**Comment by sarod** [comment]
The readme.md should be updated to stop referencing to http://repo.reficio.org/maven/org/reficio/p2-maven-plugin/.

**Comment by sarod** [comment]
https://github.com/reficio/p2-maven-plugin/pull/125
