### ISSUE TITLE
1.4.0 release not on maven central

### ISSUE THREAD

**Issue by Bananeweizen** [reficio/p2-maven-plugin#151]
According to the github releases, 1.4.0 is available since 10 days. However, it is not available on Maven central, therefore people cannot use it.

**Comment by thegreystone** [comment]
@tombujok - any chance 1.4.0 could be made available on Maven central?

**Comment by PioBeat** [comment]
As of today, my CI pipeline broke because `http://repo.reficio.org/` is not available.
I still use version 1.3.0 due to this circumstance.

Please consider moving the artifacts to Maven central.

**Comment by sudr** [comment]
+1 ...surprised by why this particular issue has remained open for 7 months.

**Comment by thegreystone** [comment]
@tombujok - are you still around? ;)

**Comment by sparsick** [comment]
Version 1.4.0 and 1.5.0 is now in Maven Central https://search.maven.org/artifact/org.reficio/p2-maven-plugin

**Comment by Bananeweizen** [comment]
Thanks. I have verified that I can use 1.5.0 now.
