### ISSUE TITLE
Cannot convert certion Maven artifact (for example org.apache.tika:tika:1.24.1)

### ISSUE THREAD

**Issue by vogella** [reficio/p2-maven-plugin#160]
Certain Maven artifacts cannot be converted via reficio. For example, if I replace the tike entry below with the following <artifact><id>org.slf4j:slf4j-simple:1.6.0</id></artifact> the build works. 

The entry seems to be an aggregator, is that not supported by reficio? https://search.maven.org/artifact/org.apache.tika/tika/1.24.1/pom

````

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001 XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.reficio.rcp</groupId>
    <artifactId>example-p2-site</artifactId>
    <packaging>pom</packaging>
    <version>1.4.1-SNAPSHOT</version>

    <build>
        <plugins>
            <plugin>
                <groupId>org.reficio</groupId>
                <artifactId>p2-maven-plugin</artifactId>
                <version>1.3.0</version>
                <executions>
                    <execution>
                        <id>default-cli</id>
                        <configuration>
                            <artifacts>
                                <!-- This entry works-->
                                <! <artifact><id>org.emfjson:emfjson-jackson:1.3.0</id></artifact>-->
                                 <!-- This entry does not work -->
                                <artifact><id>org.apache.tika:tika:1.24.1</id></artifact>
                            </artifacts>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.mortbay.jetty</groupId>
                <artifactId>jetty-maven-plugin</artifactId>
                <version>8.1.5.v20120716</version>
                <configuration>
                    <scanIntervalSeconds>10</scanIntervalSeconds>
                    <webAppSourceDirectory>${basedir}/target/repository/</webAppSourceDirectory>
                    <webApp>
                        <contextPath>/site</contextPath>
                    </webApp>
                </configuration>
            </plugin>
              <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-site-plugin</artifactId>
                <version>3.7.1</version>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-project-info-reports-plugin</artifactId>
                <version>3.0.0</version>
            </plugin>

       
        </plugins>
    </build>

</project>

````

**Comment by vogella** [comment]
Error message:

 [info] Resolving artifact=[org.apache.tika:tika:1.24.1] transitive=[true] source=[false]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/C:/Users/Lars/.m2/repository/org/codehaus/groovy/groovy-all/2.4.8/groovy-all-2.4.8.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.414 s
[INFO] Finished at: 2020-06-25T14:24:45+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.reficio:p2-maven-plugin:1.3.0:site (default-cli) on project example-p2-site: Execution default-cli of goal org.reficio:p2-maven-plugin:1.3.0:site failed: java.lang.RuntimeException: org.eclipse.aether.resolution.DependencyResolutionException: Failure to find org.apache.tika:tika:jar:1.24.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by bmarwell** [comment]
Hi @vogella,

a pull request containing an  IT would be highly appreciated! :)

**Comment by vogella** [comment]
@bmarwell Thanks for the answer but I already moved on. I'm now using the Maven PDE integration for the IDE and the Tycho support of JARs from Maven central https://www.vogella.com/tutorials/EclipseJarToPlugin/article.html#exercise-using-the-gson-library-for-plug-in-development

I close my issue.
