### ISSUE TITLE
CI does not verify

### ISSUE THREAD

**Issue by bmarwell** [reficio/p2-maven-plugin#173]
CI (currently `.travis.yaml`) only uses the package goal. Should use the verify goal instead.
+ @aalmiray ;-)

**Comment by aalmiray** [comment]
Probably, if integration tests were run using the failsafe plugin. Currently they are run by the invoker plugin bound to the `package` phase.

Bumping travis to `verify` doesn't yield any benefits at this point. 

However moving CI from Travis to GitHub actions may be a more suitable contribution IMHO.

**Comment by bmarwell** [comment]
executing `mvn verify` will fail a lot of tests.

**Comment by bmarwell** [comment]
https://github.com/reficio/p2-maven-plugin/pull/175

**Comment by aalmiray** [comment]
Does it? Interesting. Will have to dig deeper.
