### ISSUE TITLE
Housekeeping CI Infrastructure

### ISSUE THREAD

**Issue by sparsick** [reficio/p2-maven-plugin#179]
- [x] add depend a bot / renovate
- [x] remove travis ci
- [x] clean up java version
- [x] add Github Action Badge
- [x] remove maven warnings
- [x] fix windows build

**Comment by bmarwell** [comment]
java => https://github.com/reficio/p2-maven-plugin/pull/181

**Comment by bmarwell** [comment]
travis => https://github.com/reficio/p2-maven-plugin/pull/182

**Comment by bmarwell** [comment]
badges => https://github.com/reficio/p2-maven-plugin/pull/183

**Comment by bmarwell** [comment]
mvn warnings => https://github.com/reficio/p2-maven-plugin/pull/186

**Comment by sparsick** [comment]
dependabot => #187

**Comment by sparsick** [comment]
windows build => #188

**Comment by bmarwell** [comment]
Related: https://github.com/reficio/p2-maven-plugin/issues/226
