### ISSUE TITLE
Migrate Release process from Bintray to Maven Central

### ISSUE THREAD

**Issue by sparsick** [reficio/p2-maven-plugin#180]
Currently, P2 Maven Plugin is released to Bintray. Bintray is responsible for the sync to Maven Central.

[JFrog will close Bintray](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) on May 1st, so the release process should deploy to Maven Central directly

**Comment by bmarwell** [comment]
Checklist:

 - [ ] decide if using GH actions with a new team-key or the deployer should use his private key from his PC.
 - [ ] if deployer uses his own key, which key will deploy snapshots from master?
 - [ ] Deploy snapshorts to GH Packages automatically? Can be unsigned.
 - [ ] Chose a new domain / new packages. `reficio.org` is expired and cannot be used anymore.
       Suggestion: use `io.github.reficio` or move this plugin to an organization first.

**Comment by sparsick** [comment]
Deploy right on Maven Central is requested. See [Sonatype Jira Ticket](https://issues.sonatype.org/browse/OSSRH-66732)

**Comment by sparsick** [comment]
Deploy right is granted.
