### ISSUE TITLE
create binary identical JARs for unmodified input

### ISSUE THREAD

**Issue by Bananeweizen** [reficio/p2-maven-plugin#247]
The current 1.5.1 snapshot creates reproducible versions finally (due to the update of the maven-bundle-plugin dependency 4 weeks ago), if one configures the necessary settings as described here: https://maven.apache.org/guides/mini/guide-reproducible-builds.html.

That's great, now my p2 bundles are binary identical when running the build again, thereby not consuming another GB on artifactory after each build. However, JARs of transitive dependencies are still binary different, since they miss the same settings as described in the link above. Is there any way to influence the BND configuration for transitive dependencies except for making them explicit dependencies and configuring the same settings explicitly?

Would it eventually be possible to set these options internally for all calls of BND, no matter whether explicit artifact or transitive dependency artifact?
```
<_removeheaders>Bnd-LastModified</_removeheaders>
<_reproducible>true</_reproducible>
```

**Comment by sparsick** [comment]
@Bananeweizen Thanks for your hint. I will check it when I will start with issue #242 .
