### ISSUE TITLE
API Incopatibility when using the plugin with tycho version > 1.3.0

### ISSUE THREAD

**Issue by davu-all** [reficio/p2-maven-plugin#279]
When we use p2-maven-plugin 1.7.0 with a version of tycho greater than 1.3.0 we get:

[ERROR] Failed to execute goal org.reficio:p2-maven-plugin:1.7.0:site (default-cli) on project XXX: 
Execution default-cli of goal org.reficio:p2-maven-plugin:1.7.0:site failed: 
org.apache.maven.plugin.MojoExecutionException: Unable to execute mojo: Execution null of goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:1.7.0:publish-features-and-bundles failed: 
**An API incompatibility was encountered** while executing org.eclipse.tycho.extras:tycho-p2-extras-plugin:1.7.0:publish-features-and-bundles: 
**java.lang.NoSuchMethodError: org.eclipse.tycho.ArtifactDescriptor.getLocation()Ljava/io/File;**

With tycho 1.3.0 it works smoothly.

**Comment by sparsick** [comment]
@davu-all which java version you are using?

**Comment by sparsick** [comment]
@davu-all do you have a sample project for me? p2-maven-plugin is using internally Tycho 1.7.0, therefore, I don't understand your error.

**Comment by sparsick** [comment]
@davu-all in master branch is an update to Tycho Version 2.5.0. Please recheck your issue with the current snapshot version of p2 maven plugin.

**Comment by davu-all** [comment]
@sparsick  thanks for the quick answer. I'll require some time to test your snapshot. I'll be back ASAP.

**Comment by davu-all** [comment]
Hi @sparsick, 
I was finally able to test current SNAPSHOT with tycho 2.5.0 and i no longer get the error.
Thank you!

**Comment by sparsick** [comment]
@davu-all Thank you for testing. I will create ,soon as possible, a new release of the plugin
