### ISSUE TITLE
Is jetty unnecessary? Eclipse seems to support local folders in target definitions

### ISSUE THREAD

**Issue by Meai1** [reficio/p2-maven-plugin#41]
I'm sure I'm overlooking something obvious because I have yet to go through all the steps, but isn't this exactly what we are doing with jetty in the p2-maven-plugin?

![localdir_plugins](https://f.cloud.github.com/assets/1112157/1693958/b41260e8-5e98-11e3-8ec8-f99906089448.PNG)

**Comment by Virtlink** [comment]
Are you sure Tycho still doesn't support local directories? I seem to have got it working in Tycho with this repository:

```
<repository>
	<id>localp2</id>
	<url>${project.baseUri}p2/target/repository</url>
	<layout>p2</layout>
</repository>
```

Which means I don't need `jetty:run`, just `p2:site`, which could be part of the compile process.

**Comment by tombujok** [comment]
Maybe they fixed it. Does it work in eclipse too? When you import the
project. Does it compile?

**Comment by Virtlink** [comment]
It didn't work in Eclipse unless I added the repository directory manually to the manifest, [like Meai1 did](https://github.com/reficio/p2-maven-plugin/issues/41#issue-23871135). I'm quite new to Eclipse plugin development, but that's how I believe it should be.

**Comment by tombujok** [comment]
Ok, in this case it would be great if you could send a PR to the doc explaining it ;)
