### ISSUE TITLE
Custom instructions no taken into account

### ISSUE THREAD

**Issue by sstlaurent** [reficio/p2-maven-plugin#45]
I have this config with p2-maven-plugin

my project already have a manifest, but as <override>true</override> is set, it should override it. The problem is instrusctions set are not taken into account. Result is : all packages are exported, all packags are imported with optional resolution. Is this a bug or is there somthing wrong with my config.

<artifact>
<id>ca.infodata:readhl7::custom:2.0.7-SNAPSHOT</id>
<source>true</source>
<transitive>false</transitive>
<override>true</override>
<instructions>
<Import-Package>*</Import-Package>
<Export-Package>ca.infodata.readhl7</Export-Package>
</instructions>
</artifact>

Thanks

**Comment by lukejackson** [comment]
See pull request https://github.com/reficio/p2-maven-plugin/pull/72

**Comment by tombujok** [comment]
Fixed! Thanks to @lukejackson 
Will be included in the next release (1.2.0)
