### ISSUE TITLE
Add bundles with the same artifactId and versionId (but not thr same groupId)

### ISSUE THREAD

**Issue by amasse76** [reficio/p2-maven-plugin#46]
Hi,

I'm trying to build a p2 site with the following configuration :

<artifacts>
    <artifact><id>com.company.resources.xxXX:dictionary:0.0.2</id></artifact>
    <artifact><id>com.company.resources.yyYY:dictionary:0.0.2</id></artifact>
    <artifact><id>com.company.resources.zzZZ:dictionary:0.0.1</id></artifact>
</artifacts> 

There is no issue with the "com.company.resources.zzZZ:dictionary" (because the version is 0.0.1). But the "com.company.resources.xxXXdictionary" is ignored by the "com.company.resources.yyYY:dictionary" (because the same version)

Thanks
Anthony

**Comment by lukejackson** [comment]
See https://github.com/reficio/p2-maven-plugin/pull/73

**Comment by tombujok** [comment]
Fixed! Thanks to @lukejackson 
Will be included in the next release (1.2.0)
