### ISSUE TITLE
Build failed after upgrading tycho from 0.18.1 to 0.21.0

### ISSUE THREAD

**Issue by DzianisFrydliand** [reficio/p2-maven-plugin#61]
[ERROR] Failed to execute goal org.reficio:p2-maven-plugin:1.1.1:site (default-cli) on project egbdp.client.target.platform: Execution default-cli of goal org.reficio:p2-maven-plugin:1.1.1:site failed: org.apache.maven.plugin.MojoExecutionException: Unable to execute mojo: Execution null of goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:0.18.1:publish-features-and-bundles failed: A required class was missing while executing org.eclipse.tycho.extras:tycho-p2-extras-plugin:0.18.1:publish-features-and-bundles: org/eclipse/tycho/core/osgitools/targetplatform/DefaultTargetPlatform
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.eclipse.tycho.extras:tycho-p2-extras-plugin:0.18.1
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy

**Comment by DzianisFrydliand** [comment]
Any solutions for this issue?

**Comment by tombujok** [comment]
Tycho upgraded. Should be fixed. 1.2.0 released. Should be in maven central anytime.
