### ISSUE TITLE
Pb when using tycho-0.21.0 or 0.22.0

### ISSUE THREAD

**Issue by elecharny** [reficio/p2-maven-plugin#64]
Running the plugin works well when using tycho 0.20.0, but when I try with 0.21 or 0.22, I get some errors like : 

[ERROR] Failed to execute goal org.reficio:p2-maven-plugin:1.1.1:site (default-cli) on project eclipse-target-platform: Execution default-cli of goal org.reficio:p2-maven-plugin:1.1.1:site failed: org.apache.maven.plugin.MojoExecutionException: Unable to execute mojo: Execution null of goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:0.18.1:publish-features-and-bundles failed: A required class was missing while executing org.eclipse.tycho.extras:tycho-p2-extras-plugin:0.18.1:publish-features-and-bundles: org/eclipse/tycho/core/osgitools/targetplatform/DefaultTargetPlatform
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.eclipse.tycho.extras:tycho-p2-extras-plugin:0.18.1
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/elecharny/.m2/repository/org/eclipse/tycho/extras/tycho-p2-extras-plugin/0.18.1/tycho-p2-extras-plugin-0.18.1.jar
[ERROR] urls[1] = file:/Users/elecharny/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[2] = file:/Users/elecharny/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
[ERROR] urls[3] = file:/Users/elecharny/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
[ERROR] urls[4] = file:/Users/elecharny/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
[ERROR] urls[5] = file:/Users/elecharny/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
[ERROR] urls[6] = file:/Users/elecharny/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[7] = file:/Users/elecharny/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[8] = file:/Users/elecharny/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.7/plexus-utils-3.0.7.jar
[ERROR] urls[9] = file:/Users/elecharny/.m2/repository/org/codehaus/plexus/plexus-archiver/2.2/plexus-archiver-2.2.jar
[ERROR] urls[10] = file:/Users/elecharny/.m2/repository/org/codehaus/plexus/plexus-io/2.0.4/plexus-io-2.0.4.jar
[ERROR] urls[11] = file:/Users/elecharny/.m2/repository/org/eclipse/tycho/sisu-equinox-launching/0.18.1/sisu-equinox-launching-0.18.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>org.apache.directory.studio:eclipse-target-platform:2.0.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]

**Comment by jmarreroc** [comment]
+1 to this issue

**Comment by tombujok** [comment]
Could somebody submit a sample pom.xml that proves it?

**Comment by jmarreroc** [comment]
Hi Tom!
I try with [this](https://github.com/CMark/osgi-swagger-connector/blob/master/releng/com.cmark.swagger.dep.p2/pom.xml) and his pom [parent](https://github.com/CMark/osgi-swagger-connector/blob/master/releng/com.cmark.swagger.parent/pom.xml).

**Comment by tombujok** [comment]
Yes, but you don't have to include tycho in the pom.xml where p2-maven-plugin is executed.
I guess, if you comment out the parent section it will work, or if you exclude tycho from the parent project. The thing is that p2-maven-plugin has it's own tycho version that it's built against

**Comment by barclay-reg** [comment]
hi tom,
that's true, but if I need to include p2-maven-plugin into my tycho reactor project, this fails.
the following fixed it for me (putting this in the pom where p2-maven-plugin needs to be executed
```xml
<plugin>  
           <groupId>org.eclipse.tycho</groupId>  
           <artifactId>tycho-maven-plugin</artifactId>  
           <version>${tycho.version}</version>
           <extensions>false</extensions>
 </plugin>
```

**Comment by leaobr** [comment]
That's brilliant! Thanks @barclay-reg.  It is really crucial for me to declare the parent pom where p2-maven-plugin executes (the parent pom which happens to contain the tycho configs etc).  Until now I had a horrible hack to do the stuff that I needed to do by avoiding declaring the parent pom.. Glad your solutions works great! :dancers:

**Comment by ceugster** [comment]
Hi, I followed your description in http://www.reficio.org/2013/12/02/eclipse-rcp-dependency-management-done-right-with-p2-maven-plugin/ to build a local p2 repository. The build works fine and the site is visible in browser as expected. But when I try to add the site to my target platform I get missing required packages: e.g. javax.crypto that is built in java.

**Comment by lschuetze** [comment]
`<extensions>false</extensions>` makes me able to call `mvn p2:site` but I need extras enabled because I have modules with e.g., `eclipse-target-platform` packaging type.

**Comment by tombujok** [comment]
Upgraded tycho to 1.0.0
