### ISSUE TITLE
Cannot get a test p2 repo to resolve in Maven Tycho

### ISSUE THREAD

**Issue by jervin** [reficio/p2-maven-plugin#86]
I went through your tutorial example, using jetty to temporarily deploy the p2 site.  Eclipse resolved the target platform just fine, the problem is that maven command line doesn't.  I am running Maven 3.3.3.  Maven reports the following when I try to build an Eclipse plugin using the target definition.

$ mvn clean install
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.cirrus.scs.ide:com.cirrus.scs.linkclient:eclipse-plugin:0.0.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ com.cirrus.scs.ide:com.cirrus.scs.ide.parent:0.0.1-SNAPSHOT, C:\work\workspaces\workspace-test\com.cirrus.scs.ide.parent\pom.xml, line 23, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[ERROR] Internal error: java.lang.RuntimeException: Could not resolve target platform specification artifact com.cirrus.scs.ide:com.cirrus.scs.ide.targetdefinition:target:com.cirrus.scs.ide.targetdefinition:0.0.1-SNAPSHOT -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: Could not resolve target platform specification artifact com.cirrus.scs.ide:com.cirrus.scs.ide.targetdefinition:target:com.cirrus.scs.ide.targetdefinition:0.0.1-SNAPSHOT
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: Could not resolve target platform specification artifact com.cirrus.scs.ide:com.cirrus.scs.ide.targetdefinition:target:com.cirrus.scs.ide.targetdefinition:0.0.1-SNAPSHOT
        at org.eclipse.tycho.core.resolver.DefaultTargetPlatformConfigurationReader.addTargetArtifact(DefaultTargetPlatformConfigurationReader.java:389)
        at org.eclipse.tycho.core.resolver.DefaultTargetPlatformConfigurationReader.setTarget(DefaultTargetPlatformConfigurationReader.java:342)
        at org.eclipse.tycho.core.resolver.DefaultTargetPlatformConfigurationReader.getTargetPlatformConfiguration(DefaultTargetPlatformConfigurationReader.java:75)
        at org.eclipse.tycho.core.resolver.DefaultTychoResolver.setupProject(DefaultTychoResolver.java:86)
        at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:90)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        ... 11 more
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException

**Comment by jervin** [comment]
Ran the build command again with debugging information turned on:

Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T06:57:37-05:00)
Maven home: C:\work\apache-maven-3.3.3
Java version: 1.8.0_66, vendor: Oracle Corporation
Java home: C:\work\x64\Java\jdk1.8.0_66\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
[DEBUG] Created new class realm maven.api
[DEBUG] Importing foreign packages into class realm maven.api
[DEBUG]   Imported: javax.enterprise.inject.* < plexus.core
[DEBUG]   Imported: javax.enterprise.util.* < plexus.core
[DEBUG]   Imported: javax.inject.* < plexus.core
[DEBUG]   Imported: org.apache.maven.* < plexus.core
[DEBUG]   Imported: org.apache.maven.artifact < plexus.core
[DEBUG]   Imported: org.apache.maven.classrealm < plexus.core
[DEBUG]   Imported: org.apache.maven.cli < plexus.core
[DEBUG]   Imported: org.apache.maven.configuration < plexus.core
[DEBUG]   Imported: org.apache.maven.exception < plexus.core
[DEBUG]   Imported: org.apache.maven.execution < plexus.core
[DEBUG]   Imported: org.apache.maven.execution.scope < plexus.core
[DEBUG]   Imported: org.apache.maven.lifecycle < plexus.core
[DEBUG]   Imported: org.apache.maven.model < plexus.core
[DEBUG]   Imported: org.apache.maven.monitor < plexus.core
[DEBUG]   Imported: org.apache.maven.plugin < plexus.core
[DEBUG]   Imported: org.apache.maven.profiles < plexus.core
[DEBUG]   Imported: org.apache.maven.project < plexus.core
[DEBUG]   Imported: org.apache.maven.reporting < plexus.core
[DEBUG]   Imported: org.apache.maven.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.rtinfo < plexus.core
[DEBUG]   Imported: org.apache.maven.settings < plexus.core
[DEBUG]   Imported: org.apache.maven.toolchain < plexus.core
[DEBUG]   Imported: org.apache.maven.usability < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.* < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authentication < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authorization < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.events < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.observers < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.proxy < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.resource < plexus.core
[DEBUG]   Imported: org.codehaus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.* < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.component < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.configuration < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.container < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.context < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.lifecycle < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.logging < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.personality < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.* < plexus.core
[DEBUG]   Imported: org.eclipse.aether.artifact < plexus.core
[DEBUG]   Imported: org.eclipse.aether.collection < plexus.core
[DEBUG]   Imported: org.eclipse.aether.deployment < plexus.core
[DEBUG]   Imported: org.eclipse.aether.graph < plexus.core
[DEBUG]   Imported: org.eclipse.aether.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.installation < plexus.core
[DEBUG]   Imported: org.eclipse.aether.internal.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.metadata < plexus.core
[DEBUG]   Imported: org.eclipse.aether.repository < plexus.core
[DEBUG]   Imported: org.eclipse.aether.resolution < plexus.core
[DEBUG]   Imported: org.eclipse.aether.spi < plexus.core
[DEBUG]   Imported: org.eclipse.aether.transfer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.version < plexus.core
[DEBUG]   Imported: org.slf4j.* < plexus.core
[DEBUG]   Imported: org.slf4j.spi.* < plexus.core
[DEBUG] Populating class realm maven.api
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from C:\work\apache-maven-3.3.3\conf\settings.xml
[DEBUG] Reading user settings from C:\Users\jervin\.m2\settings.xml
[DEBUG] Reading global toolchains from C:\work\apache-maven-3.3.3\conf\toolchains.xml
[DEBUG] Reading user toolchains from C:\Users\jervin\.m2\toolchains.xml
[DEBUG] Using local repository at c:\work\m2repo
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for c:\work\m2repo
[INFO] Scanning for projects...
[DEBUG] Using mirror archiva.default (http://msabuild01.ad.cirrus.com:8090/repository/all/) for central (https://repo.maven.apache.org/maven2).
[DEBUG] Using mirror archiva.default (http://msabuild01.ad.cirrus.com:8090/repository/all/) for apache.snapshots (http://repository.apache.org/snapshots).
[DEBUG] Using mirror archiva.default (http://msabuild01.ad.cirrus.com:8090/repository/all/) for plexus.snapshots (https://oss.sonatype.org/content/repositories/plexus-snapshots).
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=2, ConflictMarker.markTime=0, ConflictMarker.nodeCount=79, ConflictIdSorter.graphTime=1, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=38, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=6, ConflictResolver.conflictItemCount=78, DefaultDependencyCollector.collectTime=247, DefaultDependencyCollector.transformTime=10}
[DEBUG] org.eclipse.tycho:tycho-maven-plugin:jar:0.23.1:
[DEBUG]    org.eclipse.tycho:tycho-core:jar:0.23.1:compile
[DEBUG]       org.apache.maven:maven-core:jar:3.0:compile
[DEBUG]          org.apache.maven:maven-model:jar:3.0:compile
[DEBUG]          org.apache.maven:maven-settings:jar:3.0:compile
[DEBUG]          org.apache.maven:maven-settings-builder:jar:3.0:compile
[DEBUG]          org.apache.maven:maven-repository-metadata:jar:3.0:compile
[DEBUG]          org.apache.maven:maven-artifact:jar:3.0:compile
[DEBUG]          org.apache.maven:maven-model-builder:jar:3.0:compile
[DEBUG]          org.apache.maven:maven-aether-provider:jar:3.0:runtime
[DEBUG]          org.sonatype.aether:aether-impl:jar:1.7:compile
[DEBUG]             org.sonatype.aether:aether-spi:jar:1.7:compile
[DEBUG]          org.sonatype.aether:aether-api:jar:1.7:compile
[DEBUG]          org.sonatype.aether:aether-util:jar:1.7:compile
[DEBUG]          org.sonatype.sisu:sisu-inject-plexus:jar:1.4.2:compile
[DEBUG]             org.sonatype.sisu:sisu-inject-bean:jar:1.4.2:compile
[DEBUG]                org.sonatype.sisu:sisu-guice:jar:noaop:2.1.7:compile
[DEBUG]          org.codehaus.plexus:plexus-interpolation:jar:1.14:compile
[DEBUG]          org.codehaus.plexus:plexus-classworlds:jar:2.2.3:compile
[DEBUG]          org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile
[DEBUG]             org.sonatype.plexus:plexus-cipher:jar:1.7:compile
[DEBUG]       org.apache.maven:maven-plugin-api:jar:3.0:compile
[DEBUG]       org.codehaus.plexus:plexus-utils:jar:3.0.7:compile
[DEBUG]       org.codehaus.plexus:plexus-archiver:jar:2.2:compile
[DEBUG]          org.codehaus.plexus:plexus-io:jar:2.0.5:compile
[DEBUG]       org.eclipse.tycho:org.eclipse.osgi.compatibility.state:jar:1.0.100.v20150402-1551:compile
[DEBUG]       org.eclipse.tycho:sisu-equinox-embedder:jar:0.23.1:compile
[DEBUG]          org.eclipse.tycho:org.eclipse.osgi:jar:3.10.100.v20150529-1857:compile
[DEBUG]          org.eclipse.tycho:sisu-equinox-api:jar:0.23.1:compile
[DEBUG]       org.eclipse.tycho:tycho-metadata-model:jar:0.23.1:compile
[DEBUG]          de.pdark:decentxml:jar:1.3:compile
[DEBUG]       org.eclipse.tycho:tycho-embedder-api:jar:0.23.1:compile
[DEBUG]          org.eclipse.tycho:org.eclipse.tycho.embedder.shared:jar:0.23.1:compile
[DEBUG]       org.eclipse.tycho:org.eclipse.tycho.core.shared:jar:0.23.1:compile
[DEBUG]    org.eclipse.tycho:tycho-p2-facade:jar:0.23.1:compile
[DEBUG]       org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile
[DEBUG]       org.eclipse.tycho:org.eclipse.tycho.p2.resolver.shared:jar:0.23.1:compile
[DEBUG]       org.eclipse.tycho:org.eclipse.tycho.p2.tools.shared:jar:0.23.1:compile
[DEBUG] Created new class realm extension>org.eclipse.tycho:tycho-maven-plugin:0.23.1
[DEBUG] Importing foreign packages into class realm extension>org.eclipse.tycho:tycho-maven-plugin:0.23.1
[DEBUG]   Imported:  < maven.api
[DEBUG] Populating class realm extension>org.eclipse.tycho:tycho-maven-plugin:0.23.1
[DEBUG]   Included: org.eclipse.tycho:tycho-maven-plugin:jar:0.23.1
[DEBUG]   Included: org.eclipse.tycho:tycho-core:jar:0.23.1
[DEBUG]   Included: org.sonatype.aether:aether-util:jar:1.7
[DEBUG]   Included: org.sonatype.sisu:sisu-inject-bean:jar:1.4.2
[DEBUG]   Included: org.sonatype.sisu:sisu-guice:jar:noaop:2.1.7
[DEBUG]   Included: org.codehaus.plexus:plexus-interpolation:jar:1.14
[DEBUG]   Included: org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3
[DEBUG]   Included: org.sonatype.plexus:plexus-cipher:jar:1.7
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:3.0.7
[DEBUG]   Included: org.codehaus.plexus:plexus-archiver:jar:2.2
[DEBUG]   Included: org.codehaus.plexus:plexus-io:jar:2.0.5
[DEBUG]   Included: org.eclipse.tycho:org.eclipse.osgi.compatibility.state:jar:1.0.100.v20150402-1551
[DEBUG]   Included: org.eclipse.tycho:sisu-equinox-embedder:jar:0.23.1
[DEBUG]   Included: org.eclipse.tycho:org.eclipse.osgi:jar:3.10.100.v20150529-1857
[DEBUG]   Included: org.eclipse.tycho:sisu-equinox-api:jar:0.23.1
[DEBUG]   Included: org.eclipse.tycho:tycho-metadata-model:jar:0.23.1
[DEBUG]   Included: de.pdark:decentxml:jar:1.3
[DEBUG]   Included: org.eclipse.tycho:tycho-embedder-api:jar:0.23.1
[DEBUG]   Included: org.eclipse.tycho:org.eclipse.tycho.embedder.shared:jar:0.23.1
[DEBUG]   Included: org.eclipse.tycho:org.eclipse.tycho.core.shared:jar:0.23.1
[DEBUG]   Included: org.eclipse.tycho:tycho-p2-facade:jar:0.23.1
[DEBUG]   Included: org.codehaus.plexus:plexus-component-annotations:jar:1.5.5
[DEBUG]   Included: org.eclipse.tycho:org.eclipse.tycho.p2.resolver.shared:jar:0.23.1
[DEBUG]   Included: org.eclipse.tycho:org.eclipse.tycho.p2.tools.shared:jar:0.23.1
[DEBUG] Extension realms for project com.cirrus.scs.ide:com.cirrus.scs.linkclient:eclipse-plugin:0.0.1-SNAPSHOT: [ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:0.23.1, parent: sun.misc.Launcher$AppClassLoader@70dea4e]]
[DEBUG] Created new class realm project>com.cirrus.scs.ide:com.cirrus.scs.linkclient:0.0.1-SNAPSHOT
[DEBUG] Populating class realm project>com.cirrus.scs.ide:com.cirrus.scs.linkclient:0.0.1-SNAPSHOT
[DEBUG] Looking up lifecyle mappings for packaging eclipse-plugin from ClassRealm[project>com.cirrus.scs.ide:com.cirrus.scs.linkclient:0.0.1-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]
[DEBUG] Extension realms for project com.cirrus.scs.ide:com.cirrus.scs.ide.parent:pom:0.0.1-SNAPSHOT: [ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:0.23.1, parent: sun.misc.Launcher$AppClassLoader@70dea4e]]
[DEBUG] Looking up lifecyle mappings for packaging pom from ClassRealm[project>com.cirrus.scs.ide:com.cirrus.scs.linkclient:0.0.1-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.cirrus.scs.ide:com.cirrus.scs.linkclient:eclipse-plugin:0.0.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ com.cirrus.scs.ide:com.cirrus.scs.ide.parent:0.0.1-SNAPSHOT, C:\work\workspaces\workspace-test\com.cirrus.scs.ide.parent\pom.xml, line 23, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[DEBUG] org.eclipse.tycho:tycho-maven-plugin:0.23.1 configured in MavenProject: com.cirrus.scs.ide:com.cirrus.scs.linkclient:0.0.1-SNAPSHOT @ C:\work\workspaces\workspace-test\com.cirrus.scs.linkclient\pom.xml
[DEBUG] org.eclipse.tycho:tycho-source-plugin:0.23.1 configured in MavenProject: com.cirrus.scs.ide:com.cirrus.scs.linkclient:0.0.1-SNAPSHOT @ C:\work\workspaces\workspace-test\com.cirrus.scs.linkclient\pom.xml
[DEBUG] org.eclipse.tycho:tycho-packaging-plugin:0.23.1 configured in MavenProject: com.cirrus.scs.ide:com.cirrus.scs.linkclient:0.0.1-SNAPSHOT @ C:\work\workspaces\workspace-test\com.cirrus.scs.linkclient\pom.xml
[DEBUG] org.eclipse.tycho:tycho-p2-plugin:0.23.1 configured in MavenProject: com.cirrus.scs.ide:com.cirrus.scs.linkclient:0.0.1-SNAPSHOT @ C:\work\workspaces\workspace-test\com.cirrus.scs.linkclient\pom.xml
[DEBUG] target-platform-configuration for MavenProject: com.cirrus.scs.ide:com.cirrus.scs.linkclient:0.0.1-SNAPSHOT @ C:\work\workspaces\workspace-test\com.cirrus.scs.linkclient\pom.xml:
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <pomDependencies>consider</pomDependencies>
  <target>
    <artifact>
      <groupId>com.cirrus.scs.ide</groupId>
      <artifactId>com.cirrus.scs.ide.targetdefinition</artifactId>
      <version>0.0.1-SNAPSHOT</version>
      <classifier>com.cirrus.scs.ide.targetdefinition</classifier>
    </artifact>
  </target>
  <environments>
    <environment>
      <os>linux</os>
      <ws>gtk</ws>
      <arch>x86_64</arch>
    </environment>
    <environment>
      <os>win32</os>
      <ws>win32</ws>
      <arch>x86_64</arch>
    </environment>
    <environment>
      <os>macosx</os>
      <ws>cocoa</ws>
      <arch>x86_64</arch>
    </environment>
  </environments>
</configuration>
[ERROR] Internal error: java.lang.RuntimeException: Could not resolve target platform specification artifact com.cirrus.scs.ide:com.cirrus.scs.ide.targetdefinition:target:com.cirrus.scs.ide.targetdefinition:0.0.1-SNAPSHOT -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: Could not resolve target platform specification artifact com.cirrus.scs.ide:com.cirrus.scs.ide.targetdefinition:target:com.cirrus.scs.ide.targetdefinition:0.0.1-SNAPSHOT
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: Could not resolve target platform specification artifact com.cirrus.scs.ide:com.cirrus.scs.ide.targetdefinition:target:com.cirrus.scs.ide.targetdefinition:0.0.1-SNAPSHOT
	at org.eclipse.tycho.core.resolver.DefaultTargetPlatformConfigurationReader.addTargetArtifact(DefaultTargetPlatformConfigurationReader.java:389)
	at org.eclipse.tycho.core.resolver.DefaultTargetPlatformConfigurationReader.setTarget(DefaultTargetPlatformConfigurationReader.java:342)
	at org.eclipse.tycho.core.resolver.DefaultTargetPlatformConfigurationReader.getTargetPlatformConfiguration(DefaultTargetPlatformConfigurationReader.java:75)
	at org.eclipse.tycho.core.resolver.DefaultTychoResolver.setupProject(DefaultTychoResolver.java:86)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:90)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	... 11 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException

**Comment by efstathios** [comment]
Did you try to build with: mvn p2:site ?

**Comment by jervin** [comment]
Yes I did.... here are the contents of my pom:

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.cirrus.scs.ide</groupId>
  <artifactId>example-p2-site</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>pom</packaging>
        <build>
            <plugins>
                <plugin>
                    <groupId>org.reficio</groupId>
                    <artifactId>p2-maven-plugin</artifactId>
                    <version>1.2.0-SNAPSHOT</version>
                    <executions>
                        <execution>
                            <id>default-cli</id>
                            <configuration>
                                <artifacts>
                                    
                                    
                                    <artifact><id>commons-io:commons-io:2.1</id></artifact>
                                    <artifact><id>org.apache.commons:commons-lang3:3.1</id></artifact>
                                    <artifact><id>io.grpc:grpc-all:0.9.0</id></artifact>
                                </artifacts>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>

                <plugin>
                    <groupId>org.mortbay.jetty</groupId>
                    <artifactId>jetty-maven-plugin</artifactId>
                    <version>8.1.5.v20120716</version>
                    <configuration>
                        <scanIntervalSeconds>10</scanIntervalSeconds>
                        <webAppSourceDirectory>${basedir}/target/repository/</webAppSourceDirectory>
                        <webApp>
                            <contextPath>/site</contextPath>
                        </webApp>
                   </configuration>
                </plugin>

            </plugins>
        </build>

</project>

**Comment by jervin** [comment]
Teach me to use the preview pane before posting....
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.cirrus.scs.ide</groupId>
  <artifactId>example-p2-site</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>pom</packaging>
  
        <pluginRepositories>
            <pluginRepository>
                <id>reficio</id>
                <url>http://repo.reficio.org/maven/</url>
                <snapshots>
                	<enabled>true</enabled>
                </snapshots>
            </pluginRepository>
        </pluginRepositories>
  
        <build>
            <plugins>
                <plugin>
                    <groupId>org.reficio</groupId>
                    <artifactId>p2-maven-plugin</artifactId>
                    <version>1.2.0-SNAPSHOT</version>
                    <executions>
                        <execution>
                            <id>default-cli</id>
                            <configuration>
                                <artifacts>
                                    <!-- specify your dependencies here -->
                                    <!-- groupId:artifactId:version -->
                                    <artifact><id>commons-io:commons-io:2.1</id></artifact>
                                    <artifact><id>org.apache.commons:commons-lang3:3.1</id></artifact>
                                    <artifact><id>io.grpc:grpc-all:0.9.0</id></artifact>
                                </artifacts>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>

                <plugin>
                    <groupId>org.mortbay.jetty</groupId>
                    <artifactId>jetty-maven-plugin</artifactId>
                    <version>8.1.5.v20120716</version>
                    <configuration>
                        <scanIntervalSeconds>10</scanIntervalSeconds>
                        <webAppSourceDirectory>${basedir}/target/repository/</webAppSourceDirectory>
                        <webApp>
                            <contextPath>/site</contextPath>
                        </webApp>
                   </configuration>
                </plugin>

            </plugins>
        </build>
</project>

```

**Comment by efstathios** [comment]
Which version of tycho is being used? I noticed similar problems and resolved them when I specify in the pom.xml:

    <tycho-plugins.version>0.18.1</tycho-plugins.version>

A newer version of tycho was not working in my case (e.g. 0.24.0). In the parent/other poms you can still use any version of tycho with no problems.

**Comment by jervin** [comment]
After you suggestion, I have been trying multiple versions, 0.18.0, 0.18.1, 0.23.1, and 0.24.0 with no success.  Do you know if Tycho gets confused with some sites using features, whereas the generated p2 site has categories and is referenced by plugin?

Also thanks for the quick response, it has helped eliminate possible causes quickly.

**Comment by jervin** [comment]
I have it building now.  The thing was that I was running the maven build from the parent where all the modules are defined.  The order of those modules seems to matter a great deal.  I will close this issue out, thanks for your help. :)
