### ISSUE TITLE
Publish latest version to reficio repo?

### ISSUE THREAD

**Issue by kdvolder** [reficio/p2-maven-plugin#95]
I'm hitting this bug: https://issues.apache.org/jira/browse/FELIX-4005

From the looks of things, what's in the github repo here has already been updated to use more recent version of BND. So this probem has already been fixed.

But it seems the fix has not been published to the maven repo so unless I build my own version of p2-maven-plugin I am getting something really old that doesn't work on 'modern' jar files.

I just built p2-maven-plugin locally and that one seems to work fine. So why not publish it?

**Comment by tombujok** [comment]
I would love to release soon, but there's one pending issue https://github.com/reficio/p2-maven-plugin/pull/75
I'm looking for sb who could rebase it and merge minor conflicts.

**Comment by kdvolder** [comment]
I don't see why you have to wait for that to publish a new snapshot. The previously published snapshot is several years old and not usable anymore.

**Comment by beihaifeiwu** [comment]
+1

**Comment by Venorcis** [comment]
+ if this resolves the Java 8 issues

**Comment by kdvolder** [comment]
>  if this resolves the Java 8 issues

Yes it does.

**Comment by Venorcis** [comment]
@tombujok could you please release a new snapshot version?

**Comment by greensopinion** [comment]
It seems that #75 has stalled out.  Do we really need to wait on that to get Java 8 support in?  I'd love to see this released so that we can use this with Java 8.

**Comment by greensopinion** [comment]
Looks like I should have checked your twitter stream - is this now released? http://search.maven.org/#search%7Cga%7C1%7Cp2-maven-plugin

**Comment by tombujok** [comment]
Yep, it's been released. Sorry, didn't notice this issue to notify you guys.
Is anyone of you interested in doing small contributions to keep the project rolling?

**Comment by greensopinion** [comment]
If something comes up that affects me I'll be happy to contribute.  Unfortunately I'm spread pretty thin over multiple other projects and can't contribute more than that.  Thanks for all you've done so far!
