### ISSUE TITLE
Inconsistent timestamp schemas for snapshot artifacts

### ISSUE THREAD

**Issue by mquirin** [reficio/p2-maven-plugin#99]
I have the following two artifacts:
(in calculateProposedVersion(...) in P2Helper)

Scenario A:
artifact.baseVersion: "3.21-SNAPSHOT"
artifact.version: "3.21-20160609.210406-362"
artifact.snapshot: true

Scenario B:
artifact.baseVersion: "3.21-SNAPSHOT"
artifact.version: "3.21-SNAPSHOT"
artifact.snapshot: true

The resulting bundle names are:
Scenario A: <group><artifact>_3.21.0.20160609_210406-362.jar
Scenario B: <group><artifact>_3.21.0.20160610144645.jar

This means the naming convention is 
a) inconsistent
b) seems to also confuse eclipse pde at times

From the Maven FAQ (http://maven.apache.org/plugins/maven-assembly-plugin/faq.html)
${artifact.version} : The artifact classifier.
${artifact.baseVersion} : The artifact base version (For a SNAPSHOT it will be always -SNAPSHOT and not its timestamp even if you didn't built it yourself).

In order to fix this issue I propose 
- to only check the snapshot flag to determine if the artifact is a snapshot
- use the baseVersion to generate the output bundle name
  (behave as if isProperSnapshotVersion() would always return false)

**Comment by tombujok** [comment]
Has been fixed by the PR mentioned.
